[program:import]
directory=/home/web/www/download_admin
command=php /home/web/www/download_admin/think queue:listen --queue import --sleep 5 --delay 5 --timeout=0
stderr_logfile=/home/web/log/supervisor/import_error.log
stdout_logfile=/home/web/log/supervisor/import.log
autostart=true
autorestart=true
user = www-data
