server {
    listen    8585;
    server_name  localhost;

    client_max_body_size 50M;

    #charset koi8-r;

    index  index.html index.htm index.php;

    root /Users/qiaoyuan/www/php/base_admin/public;

    # 配置图片访问路径
    location /image/ {
        alias /Users/qiaoyuan/www/php/base_admin/public/image/;
        autoindex on; # 可选，显示目录列表
    }

    location /doc/ {
        alias /Users/qiaoyuan/www/php/base_admin/public/doc/;
        autoindex on; # 可选，显示目录列表
    }

    location / {
        if (!-e $request_filename) {
            rewrite  ^(.*)$  /index.php?s=$1  last;
            break;
        }
    }

    location ~ \.php(.*)$ {
        fastcgi_pass 127.0.0.1:9000; # 连接PHP-FPM（端口/套接字根据实际调整）
        fastcgi_index index.php;
        fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        include fastcgi_params;
    }

    # 禁止访问隐藏文件（如.git/.env）
    location ~ /\. {
        deny all;
    }
}
